title: Andy Jiménez # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><b><span style="color:blue">Financial Data Scientist</span></b>
  <br><b> Bachelor's Degree in Finance</b>.
  <br>Programming projects in Finance fields such as Financial Modelling, Stock Prediction, Portfolio Optimization, Valuation, Forecasting Time-series, etc.
  <br><br>
  <a href="https://www.linkedin.com/in/andresjimenezbonilla/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://andjimbon.github.io/">Home</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
